In [1]:
# convert processed.json to dataframe
import json
import pandas as pd

with open("./data/processed.json") as data_file:
    json_data = json.load(data_file)

    affiliates = [d.get("affiliates") for d in json_data]
    key = [d.get("key") for d in json_data]
    title = [d.get("title") for d in json_data]
    level = [d.get("level") for d in json_data]
    num_of_projects = [d.get("num_of_projects") for d in json_data]
    tags = [d.get("tags") for d in json_data]
    average_rating = [d.get("average_rating") for d in json_data]
    count = [d.get("count") for d in json_data]
    stats = [d.get("stats") for d in json_data]


    data = {
        "title": title,
        "affiliates": affiliates,
        "key": key,
        "level": level,
        "num_of_projects": num_of_projects,
        "tags": tags,
        "average_rating": average_rating,
        "count": count,
        "stats": stats,
    }

    df = pd.DataFrame(data, columns = ["title", "affiliates", "key", "level", "num_of_projects", "tags", "average_rating", "count", "stats"])

    print(df)


# df = pd.read_json("./data/processed.json")

title  \
0                               Product Manager
1                       AI for Business Leaders
2     Intro to Machine Learning with TensorFlow
3                                   UX Designer
4                                Data Streaming
..                                          ...
58                      Artificial Intelligence
59                      Front End Web Developer
60          Full Stack Web Developer Nanodegree
61         Machine Learning Engineer Nanodegree
62  Secure and Private AI Scholarship Challenge

                                           affiliates    key         level  \
0                                                  []  nd036      beginner
1                                                  []  nd054  intermediate
2   [{'image': '/assets/iridium/images/shared/part...  nd230      beginner
3                                                  []  nd578      beginner
4                                                  []  nd029      advanced
..                                                ...    ...           ...
58                                                 []  nd898      advanced
59                                               None  nd001  intermediate
60                                               None  nd004  intermediate
61                                               None  nd009  intermediate
62                                               None  nd185      advanced

    num_of_projects                                               tags  \
0                 0  [Product Marketing, Pricing Strategy, Market R...
1                 0  [Deep Learning, Unsupervised Learning, Compute...
2                 0                         [Machine Learning, Google]
3                 0  [UX, UI, Wireframing, Product Design, UX/UI, U...
4                 0  [faust, python, ksql, sparksql, apache avro, a...
..              ...                                                ...
58                0  [Deep learning, Intro to AI, Hill Climbing, Ge...
59                0  [css, html, javascript, UX Design, User interf...
60                0                                               None
61                0                                               None
62                0                                               None

    average_rating  count                                              stats
0         4.568627     51  [{'rating': 5, 'count': 32, 'percentage': 62.7...
1         5.000000      2  [{'rating': 5, 'count': 2, 'percentage': 100, ...
2         4.847826     46  [{'rating': 5, 'count': 39, 'percentage': 84.7...
3         4.724324    185  [{'rating': 5, 'count': 145, 'percentage': 78....
4         3.884058     68  [{'rating': 5, 'count': 28, 'percentage': 40.5...
..             ...    ...                                                ...
58        4.500000     80  [{'rating': 5, 'count': 87, 'percentage': 71.3...
59        4.663966   1301  [{'rating': 5, 'count': 2192, 'percentage': 77...
60        4.559016    504  [{'rating': 5, 'count': 866, 'percentage': 70....
61        4.609375    669  [{'rating': 5, 'count': 1285, 'percentage': 74...
62        4.791411    105  [{'rating': 5, 'count': 273, 'percentage': 83....

[63 rows x 9 columns]

In [10]:
df1 = df["average_ratings"]

df1.describe()

count    63.000000
mean      4.416854
std       0.877063
min       0.000000
25%       4.500000
50%       4.588435
75%       4.711656
max       5.000000
Name: average_rating, dtype: float64

In [2]:

sample_data = {
    "title": data.get("title"),
    "average_rating": data.get("average_rating"),
}

df_ratings = pd.DataFrame(sample_data)

df_ratings.nsmallest(20, "average_rating").plot(figsize=(10,5), kind="bar", legend=True, x="title", y="average_rating")
df_ratings.nlargest(20, "average_rating").plot(figsize=(10,5), kind="bar", legend=True, x="title", y="average_rating")

In [4]:

# slice data to work with dataframe better
# and drop none values

new_df = df[
    ["title", "average_rating", "key", "count", "level", "stats", "num_of_projects", "tags"]
].dropna()

print(new_df)

title  average_rating        key  \
0                             Product Manager        4.568627      nd036
1                     AI for Business Leaders        5.000000      nd054
2   Intro to Machine Learning with TensorFlow        4.847826      nd230
3                                 UX Designer        4.724324      nd578
4                              Data Streaming        3.884058      nd029
5                     Front End Web Developer        4.556561     nd0011
6                    Full Stack Web Developer        4.536585     nd0044
7                              Java Developer        2.906250      nd035
8                          AI Product Manager        4.252252      nd088
9                      Sensor Fusion Engineer        4.720930      nd313
10                         Data Visualization        4.688889      nd197
11                            Cloud Developer        4.376404     nd9990
12                      Cloud DevOps Engineer        4.474860     nd9991
13     Intro to Machine Learning with PyTorch        4.748148      nd229
14                                        C++        4.466368      nd213
15             Data Structures and Algorithms        4.547872      nd256
16        Programming for Data Science with R        4.833333      nd118
17                              Data Engineer        4.481229      nd027
18                        Marketing Analytics        4.696203      nd028
19                Introduction to Programming        4.627980      nd000
20                               Data Analyst        4.560143      nd002
21                      Become a Data Analyst        4.722488  nd002-ent
22                              iOS Developer        4.610306      nd003
23                              iOS Developer        5.000000   nd003-br
24          Predictive Analytics for Business        4.641667     nd008t
25            Business Analyst for Enterprise        4.548387  nd008-ent
26                           Business Analyst        4.570621      nd008
27                  Machine Learning Engineer        4.533333     nd009t
28                  Self Driving Car Engineer        4.746765      nd013
29                               VR Developer        4.348243      nd017
30                          Digital Marketing        4.681858      nd018
31                                      React        4.588435      nd019
32                      Mobile Web Specialist        4.807229      nd024
33                             Data Scientist        4.527559      nd025
34                 AI Programming with Python        4.548165      nd089
35                         Business Analytics        4.681579      nd098
36            Data Foundations for Enterprise        4.568000  nd100-ent
37                              Deep Learning        4.639004      nd101
38   Programming for Data Science with Python        4.702381      nd104
39                             VR Foundations        5.000000      nd105
40                              VR Mobile 360        0.000000      nd106
41                          VR High-Immersion        0.000000      nd107
42                 Intro to Self-Driving Cars        4.680217      nd113
43                Learn Unreal VR Foundations        4.857143      nd117
44                                 Google Ads        4.500000      nd124
45                       Blockchain Developer        4.296703     nd1309
46                  Design Sprint Foundations        4.547945      nd201
47                 Robotics Software Engineer        4.468599      nd209
48                           Google Analytics        3.000000      nd253
49  Flying Car and Autonomous Flight Engineer        4.487395      nd787
50                          Android Developer        4.734921      nd801
51                          Android Developer        4.653846   nd801-br
52                             Android Basics        4.846098      nd803
53                             Android Basics        4.884615   nd803-br
54        Artificial Intelligence for Trading        4.504950      nd880
55                            Computer Vision        4.591440      nd891
56                Natural Language Processing        4.443038      nd892
57                Deep Reinforcement Learning        4.676259      nd893
58                    Artificial Intelligence        4.500000      nd898
59                    Front End Web Developer        4.663966      nd001

    count          level                                              stats  \
0      51       beginner  [{'rating': 5, 'count': 32, 'percentage': 62.7...
1       2   intermediate  [{'rating': 5, 'count': 2, 'percentage': 100, ...
2      46       beginner  [{'rating': 5, 'count': 39, 'percentage': 84.7...
3     185       beginner  [{'rating': 5, 'count': 145, 'percentage': 78....
4      68       advanced  [{'rating': 5, 'count': 28, 'percentage': 40.5...
5     221   intermediate  [{'rating': 5, 'count': 159, 'percentage': 71....
6     164   intermediate  [{'rating': 5, 'count': 109, 'percentage': 66....
7      32   Intermediate  [{'rating': 5, 'count': 7, 'percentage': 21.87...
8     215       Beginner  [{'rating': 5, 'count': 126, 'percentage': 56....
9      82       Advanced  [{'rating': 5, 'count': 67, 'percentage': 77.9...
10     45       Beginner  [{'rating': 5, 'count': 35, 'percentage': 77.7...
11    177  Intermediate   [{'rating': 5, 'count': 116, 'percentage': 65....
12    179  Intermediate   [{'rating': 5, 'count': 116, 'percentage': 64....
13    129       Beginner  [{'rating': 5, 'count': 105, 'percentage': 77....
14    219   Intermediate  [{'rating': 5, 'count': 149, 'percentage': 66....
15    181   Intermediate  [{'rating': 5, 'count': 143, 'percentage': 76....
16     12       beginner  [{'rating': 5, 'count': 10, 'percentage': 83.3...
17    283   intermediate  [{'rating': 5, 'count': 197, 'percentage': 67....
18     76       beginner  [{'rating': 5, 'count': 63, 'percentage': 79.7...
19   1215       beginner  [{'rating': 5, 'count': 1660, 'percentage': 74...
20    984   intermediate  [{'rating': 5, 'count': 1423, 'percentage': 72...
21    161   intermediate  [{'rating': 5, 'count': 170, 'percentage': 81....
22    301   intermediate  [{'rating': 5, 'count': 456, 'percentage': 73....
23      0   intermediate  [{'rating': 5, 'count': 4, 'percentage': 100, ...
24    106   intermediate  [{'rating': 5, 'count': 91, 'percentage': 75.8...
25     11       beginner  [{'rating': 5, 'count': 22, 'percentage': 70.9...
26    162       beginner  [{'rating': 5, 'count': 259, 'percentage': 73....
27    247       advanced  [{'rating': 5, 'count': 249, 'percentage': 72....
28    520       advanced  [{'rating': 5, 'count': 897, 'percentage': 82....
29    159   intermediate  [{'rating': 5, 'count': 210, 'percentage': 67....
30    663       beginner  [{'rating': 5, 'count': 895, 'percentage': 78....
31    308   intermediate  [{'rating': 5, 'count': 451, 'percentage': 76....
32    163       advanced  [{'rating': 5, 'count': 287, 'percentage': 86....
33    217       advanced  [{'rating': 5, 'count': 182, 'percentage': 71....
34    295       beginner  [{'rating': 5, 'count': 328, 'percentage': 75....
35    369       beginner  [{'rating': 5, 'count': 298, 'percentage': 78....
36     52       beginner  [{'rating': 5, 'count': 102, 'percentage': 81....
37   1043   intermediate  [{'rating': 5, 'count': 1661, 'percentage': 76...
38    239       beginner  [{'rating': 5, 'count': 195, 'percentage': 77....
39      0       beginner  [{'rating': 5, 'count': 1, 'percentage': 100, ...
40      0   intermediate                                                 []
41      0   intermediate                                                 []
42    224   intermediate  [{'rating': 5, 'count': 288, 'percentage': 78....
43      4   intermediate  [{'rating': 5, 'count': 6, 'percentage': 85.71...
44      7       beginner  [{'rating': 5, 'count': 24, 'percentage': 70.5...
45     62   intermediate  [{'rating': 5, 'count': 56, 'percentage': 61.5...
46     46       beginner  [{'rating': 5, 'count': 100, 'percentage': 68....
47    133       advanced  [{'rating': 5, 'count': 143, 'percentage': 69....
48      2   intermediate  [{'rating': 5, 'count': 1, 'percentage': 50, '...
49     84       advanced  [{'rating': 5, 'count': 89, 'percentage': 74.7...
50    901   intermediate  [{'rating': 5, 'count': 1616, 'percentage': 81...
51      6   intermediate  [{'rating': 5, 'count': 23, 'percentage': 88.4...
52   1399       beginner  [{'rating': 5, 'count': 2415, 'percentage': 88...
53      5       beginner  [{'rating': 5, 'count': 23, 'percentage': 88.4...
54    185   intermediate  [{'rating': 5, 'count': 138, 'percentage': 68....
55    214       advanced  [{'rating': 5, 'count': 184, 'percentage': 71....
56    129       advanced  [{'rating': 5, 'count': 106, 'percentage': 67....
57    117       advanced  [{'rating': 5, 'count': 105, 'percentage': 75....
58     80       advanced  [{'rating': 5, 'count': 87, 'percentage': 71.3...
59   1301   intermediate  [{'rating': 5, 'count': 2192, 'percentage': 77...

    num_of_projects                                               tags
0                 0  [Product Marketing, Pricing Strategy, Market R...
1                 0  [Deep Learning, Unsupervised Learning, Compute...
2                 0                         [Machine Learning, Google]
3                 0  [UX, UI, Wireframing, Product Design, UX/UI, U...
4                 0  [faust, python, ksql, sparksql, apache avro, a...
5                 6  [object oriented, object-oriented, UI, UX, Use...
6                 5  [computer science, front-end, frontend, javasc...
7                 4  [Persistent layers, Jenkins, CI/CD, Microservi...
8                 3  [AI Product Manager, AI in business, ML in bus...
9                 4  [Lidar, Radar, Kalman Filters, Radar Calibrati...
10                4  [data visualization, Build Dashboard, Dashboar...
11                5  [cloud engineering, Cloud Basics, Cloud Founda...
12                5  [cloud, devops, Cloud Basics, Cloud Foundation...
13                4  [pyhton, python, sql, predictive, supervised, ...
14                5  [classes, structures, pointers, leakage, funct...
15                4  [big O notiation, recursion, trees, maps, hash...
16                3  [R, nd118, SQL, Advance SQl, Basic Data Scienc...
17                6  [data pipelines, data lakes, Data model, Apach...
18                8  [digital marketing, google, Data Analytics, Da...
19                5  [python, css, html, javascript, HTML, CSS, Pyt...
20                0  [Dataset, Data Science, Data Storage, Data Pro...
21               22                            [r, hadoop, python, d3]
22               14  [swift, iOS, Swift, Make App, Make iOS App, Bu...
23                0                                                 []
24                8  [Data Analytics, No Coding, Alyterx, Tableau, ...
25                9                                                 []
26                9                                                 []
27                4  [python, Machine Learning, Deep learning, AI, ...
28               14  [Computer Vision, Sensor Fusion, Localization,...
29               13               [unity, vr, virtual reality, unreal]
30                8  [No Coding, Social Media Marketing, Social Med...
31                3  [React, Front-end , Redux, React Native, React...
32                3                                                 []
33                0  [Data Analytics, Python, Data Wrangling, ETL p...
34                0  [Python, Numpy , Pandas, neural network, Anaco...
35                0  [Excel, No Coding, SQL, Tableau, Descriptive S...
36                4                                                 []
37                5  [Neural Network, AI, Pytorch, Numpy, CNN, Mach...
38                3  [Data Analytics, SQL, SQL join, Python, Numpy,...
39                0                                  [Virtual Reality]
40                0                                  [Virtual Reality]
41                0                                  [Virtual Reality]
42                8  [Self Driving Car, Automation, Bayesian Thinki...
43                0                                                 []
44                2                                                 []
45                0  [Block chain, Blockchain, Backend, Java script...
46                4                                                 []
47                0  [ROS, Gazebo, Localization, Mapping, SLAM, Nav...
48                0                                                 []
49                0  [Drone, Drone Robotics, Flying Car, Drone Inte...
50               14  [android, App Development, Android App Develop...
51                0                                                 []
52               12  [mobile, apps, development, android, App Devel...
53                0                                                 []
54                0  [Trading, World Quant, quantitative analysis,,...
55                0  [CNN, Recognise Faces, Image Captioning, RNN, ...
56                0  [nlp, Deep learning, neural network, machine l...
57                0  [Viedeo Games, neural network, neural networks...
58                0  [Deep learning, Intro to AI, Hill Climbing, Ge...
59                0  [css, html, javascript, UX Design, User interf...

In [5]:

# lets see if we can group the degrees by levels
df_levels = new_df.groupby(["level"]).mean()
df_levels.head()

               average_rating       count  num_of_projects
level
Advanced             4.720930   82.000000         4.000000
Beginner             4.563096  129.666667         3.666667
Intermediate         3.973497  144.000000         4.333333
Intermediate         4.425632  178.000000         5.000000
advanced             4.515061  179.272727         1.909091

In [14]:

# looks like advanced / beginner and intermediate have duplicate entries in levels 
# should fix that but can't be bothered right now

# Todo 
# lets filter the df by removing num_of_projects
filtered_df = new_df.loc[new_df["num_of_projects"] > 0]


# filtered_df
# lets sort the projects by rating
# (using pandas 1.0.0 - we need to use .sort_values instead of .sort)
sorted_df = filtered_df.sort_values(by =["average_rating"], ascending=False)


# lets now sort the sorted_df by average_rating, count, level and num_of_projects
sorted_df = sorted_df.sort_values(by = ["level", "average_rating", "count", "num_of_projects"], ascending = False)

sorted_df.head()

,title,average_rating,key,count,level,stats,num_of_projects,tags
50,Android Developer,4.734921,nd801,901,intermediate,"[{'rating': 5, 'count': 1616, 'percentage': 81...",14,"[android, App Development, Android App Develop..."
21,Become a Data Analyst,4.722488,nd002-ent,161,intermediate,"[{'rating': 5, 'count': 170, 'percentage': 81....",22,"[r, hadoop, python, d3]"
42,Intro to Self-Driving Cars,4.680217,nd113,224,intermediate,"[{'rating': 5, 'count': 288, 'percentage': 78....",8,"[Self Driving Car, Automation, Bayesian Thinki..."
24,Predictive Analytics for Business,4.641667,nd008t,106,intermediate,"[{'rating': 5, 'count': 91, 'percentage': 75.8...",8,"[Data Analytics, No Coding, Alyterx, Tableau, ..."
37,Deep Learning,4.639004,nd101,1043,intermediate,"[{'rating': 5, 'count': 1661, 'percentage': 76...",5,"[Neural Network, AI, Pytorch, Numpy, CNN, Mach..."

In [19]:
# lets now handle the level where it is capitalized

sorted_df.loc[sorted_df["level"].str.contains("Advanced"), "level"] = "advanced"
sorted_df.loc[sorted_df["level"].str.contains("Intermediate"), "level"] = "intermediate"
sorted_df.loc[sorted_df["level"].str.contains("Beginner"), "level"] = "beginner"

sorted_df

,title,average_rating,key,count,level,stats,num_of_projects,tags
50,Android Developer,4.734921,nd801,901,intermediate,"[{'rating': 5, 'count': 1616, 'percentage': 81...",14,"[android, App Development, Android App Develop..."
21,Become a Data Analyst,4.722488,nd002-ent,161,intermediate,"[{'rating': 5, 'count': 170, 'percentage': 81....",22,"[r, hadoop, python, d3]"
42,Intro to Self-Driving Cars,4.680217,nd113,224,intermediate,"[{'rating': 5, 'count': 288, 'percentage': 78....",8,"[Self Driving Car, Automation, Bayesian Thinki..."
24,Predictive Analytics for Business,4.641667,nd008t,106,intermediate,"[{'rating': 5, 'count': 91, 'percentage': 75.8...",8,"[Data Analytics, No Coding, Alyterx, Tableau, ..."
37,Deep Learning,4.639004,nd101,1043,intermediate,"[{'rating': 5, 'count': 1661, 'percentage': 76...",5,"[Neural Network, AI, Pytorch, Numpy, CNN, Mach..."
22,iOS Developer,4.610306,nd003,301,intermediate,"[{'rating': 5, 'count': 456, 'percentage': 73....",14,"[swift, iOS, Swift, Make App, Make iOS App, Bu..."
31,React,4.588435,nd019,308,intermediate,"[{'rating': 5, 'count': 451, 'percentage': 76....",3,"[React, Front-end , Redux, React Native, React..."
5,Front End Web Developer,4.556561,nd0011,221,intermediate,"[{'rating': 5, 'count': 159, 'percentage': 71....",6,"[object oriented, object-oriented, UI, UX, Use..."
6,Full Stack Web Developer,4.536585,nd0044,164,intermediate,"[{'rating': 5, 'count': 109, 'percentage': 66....",5,"[computer science, front-end, frontend, javasc..."
17,Data Engineer,4.481229,nd027,283,intermediate,"[{'rating': 5, 'count': 197, 'percentage': 67....",6,"[data pipelines, data lakes, Data model, Apach..."
29,VR Developer,4.348243,nd017,159,intermediate,"[{'rating': 5, 'count': 210, 'percentage': 67....",13,"[unity, vr, virtual reality, unreal]"
52,Android Basics,4.846098,nd803,1399,beginner,"[{'rating': 5, 'count': 2415, 'percentage': 88...",12,"[mobile, apps, development, android, App Devel..."
16,Programming for Data Science with R,4.833333,nd118,12,beginner,"[{'rating': 5, 'count': 10, 'percentage': 83.3...",3,"[R, nd118, SQL, Advance SQl, Basic Data Scienc..."
38,Programming for Data Science with Python,4.702381,nd104,239,beginner,"[{'rating': 5, 'count': 195, 'percentage': 77....",3,"[Data Analytics, SQL, SQL join, Python, Numpy,..."
18,Marketing Analytics,4.696203,nd028,76,beginner,"[{'rating': 5, 'count': 63, 'percentage': 79.7...",8,"[digital marketing, google, Data Analytics, Da..."
30,Digital Marketing,4.681858,nd018,663,beginner,"[{'rating': 5, 'count': 895, 'percentage': 78....",8,"[No Coding, Social Media Marketing, Social Med..."
19,Introduction to Programming,4.627980,nd000,1215,beginner,"[{'rating': 5, 'count': 1660, 'percentage': 74...",5,"[python, css, html, javascript, HTML, CSS, Pyt..."
26,Business Analyst,4.570621,nd008,162,beginner,"[{'rating': 5, 'count': 259, 'percentage': 73....",9,[]
36,Data Foundations for Enterprise,4.568000,nd100-ent,52,beginner,"[{'rating': 5, 'count': 102, 'percentage': 81....",4,[]
25,Business Analyst for Enterprise,4.548387,nd008-ent,11,beginner,"[{'rating': 5, 'count': 22, 'percentage': 70.9...",9,[]
46,Design Sprint Foundations,4.547945,nd201,46,beginner,"[{'rating': 5, 'count': 100, 'percentage': 68....",4,[]
44,Google Ads,4.500000,nd124,7,beginner,"[{'rating': 5, 'count': 24, 'percentage': 70.5...",2,[]
32,Mobile Web Specialist,4.807229,nd024,163,advanced,"[{'rating': 5, 'count': 287, 'percentage': 86....",3,[]
28,Self Driving Car Engineer,4.746765,nd013,520,advanced,"[{'rating': 5, 'count': 897, 'percentage': 82....",14,"[Computer Vision, Sensor Fusion, Localization,..."
27,Machine Learning Engineer,4.533333,nd009t,247,advanced,"[{'rating': 5, 'count': 249, 'percentage': 72....",4,"[python, Machine Learning, Deep learning, AI, ..."
12,Cloud DevOps Engineer,4.474860,nd9991,179,intermediate,"[{'rating': 5, 'count': 116, 'percentage': 64....",5,"[cloud, devops, Cloud Basics, Cloud Foundation..."
11,Cloud Developer,4.376404,nd9990,177,intermediate,"[{'rating': 5, 'count': 116, 'percentage': 65....",5,"[cloud engineering, Cloud Basics, Cloud Founda..."
15,Data Structures and Algorithms,4.547872,nd256,181,intermediate,"[{'rating': 5, 'count': 143, 'percentage': 76....",4,"[big O notiation, recursion, trees, maps, hash..."
14,C++,4.466368,nd213,219,intermediate,"[{'rating': 5, 'count': 149, 'percentage': 66....",5,"[classes, structures, pointers, leakage, funct..."
7,Java Developer,2.906250,nd035,32,intermediate,"[{'rating': 5, 'count': 7, 'percentage': 21.87...",4,"[Persistent layers, Jenkins, CI/CD, Microservi..."
13,Intro to Machine Learning with PyTorch,4.748148,nd229,129,beginner,"[{'rating': 5, 'count': 105, 'percentage': 77....",4,"[pyhton, python, sql, predictive, supervised, ..."
10,Data Visualization,4.688889,nd197,45,beginner,"[{'rating': 5, 'count': 35, 'percentage': 77.7...",4,"[data visualization, Build Dashboard, Dashboar..."
8,AI Product Manager,4.252252,nd088,215,beginner,"[{'rating': 5, 'count': 126, 'percentage': 56....",3,"[AI Product Manager, AI in business, ML in bus..."
9,Sensor Fusion Engineer,4.720930,nd313,82,advanced,"[{'rating': 5, 'count': 67, 'percentage': 77.9...",4,"[Lidar, Radar, Kalman Filters, Radar Calibrati..."

In [24]:
# let check sorted_df
sorted_df.groupby(["level"]).mean()

sorted_df = sorted_df.sort_values(by = ["level", "average_rating", "count", "num_of_projects"], ascending = False)

# we're done massging here
sorted_df

,title,average_rating,key,count,level,stats,num_of_projects,tags
50,Android Developer,4.734921,nd801,901,intermediate,"[{'rating': 5, 'count': 1616, 'percentage': 81...",14,"[android, App Development, Android App Develop..."
21,Become a Data Analyst,4.722488,nd002-ent,161,intermediate,"[{'rating': 5, 'count': 170, 'percentage': 81....",22,"[r, hadoop, python, d3]"
42,Intro to Self-Driving Cars,4.680217,nd113,224,intermediate,"[{'rating': 5, 'count': 288, 'percentage': 78....",8,"[Self Driving Car, Automation, Bayesian Thinki..."
24,Predictive Analytics for Business,4.641667,nd008t,106,intermediate,"[{'rating': 5, 'count': 91, 'percentage': 75.8...",8,"[Data Analytics, No Coding, Alyterx, Tableau, ..."
37,Deep Learning,4.639004,nd101,1043,intermediate,"[{'rating': 5, 'count': 1661, 'percentage': 76...",5,"[Neural Network, AI, Pytorch, Numpy, CNN, Mach..."
22,iOS Developer,4.610306,nd003,301,intermediate,"[{'rating': 5, 'count': 456, 'percentage': 73....",14,"[swift, iOS, Swift, Make App, Make iOS App, Bu..."
31,React,4.588435,nd019,308,intermediate,"[{'rating': 5, 'count': 451, 'percentage': 76....",3,"[React, Front-end , Redux, React Native, React..."
5,Front End Web Developer,4.556561,nd0011,221,intermediate,"[{'rating': 5, 'count': 159, 'percentage': 71....",6,"[object oriented, object-oriented, UI, UX, Use..."
15,Data Structures and Algorithms,4.547872,nd256,181,intermediate,"[{'rating': 5, 'count': 143, 'percentage': 76....",4,"[big O notiation, recursion, trees, maps, hash..."
6,Full Stack Web Developer,4.536585,nd0044,164,intermediate,"[{'rating': 5, 'count': 109, 'percentage': 66....",5,"[computer science, front-end, frontend, javasc..."
17,Data Engineer,4.481229,nd027,283,intermediate,"[{'rating': 5, 'count': 197, 'percentage': 67....",6,"[data pipelines, data lakes, Data model, Apach..."
12,Cloud DevOps Engineer,4.474860,nd9991,179,intermediate,"[{'rating': 5, 'count': 116, 'percentage': 64....",5,"[cloud, devops, Cloud Basics, Cloud Foundation..."
14,C++,4.466368,nd213,219,intermediate,"[{'rating': 5, 'count': 149, 'percentage': 66....",5,"[classes, structures, pointers, leakage, funct..."
11,Cloud Developer,4.376404,nd9990,177,intermediate,"[{'rating': 5, 'count': 116, 'percentage': 65....",5,"[cloud engineering, Cloud Basics, Cloud Founda..."
29,VR Developer,4.348243,nd017,159,intermediate,"[{'rating': 5, 'count': 210, 'percentage': 67....",13,"[unity, vr, virtual reality, unreal]"
7,Java Developer,2.906250,nd035,32,intermediate,"[{'rating': 5, 'count': 7, 'percentage': 21.87...",4,"[Persistent layers, Jenkins, CI/CD, Microservi..."
52,Android Basics,4.846098,nd803,1399,beginner,"[{'rating': 5, 'count': 2415, 'percentage': 88...",12,"[mobile, apps, development, android, App Devel..."
16,Programming for Data Science with R,4.833333,nd118,12,beginner,"[{'rating': 5, 'count': 10, 'percentage': 83.3...",3,"[R, nd118, SQL, Advance SQl, Basic Data Scienc..."
13,Intro to Machine Learning with PyTorch,4.748148,nd229,129,beginner,"[{'rating': 5, 'count': 105, 'percentage': 77....",4,"[pyhton, python, sql, predictive, supervised, ..."
38,Programming for Data Science with Python,4.702381,nd104,239,beginner,"[{'rating': 5, 'count': 195, 'percentage': 77....",3,"[Data Analytics, SQL, SQL join, Python, Numpy,..."
18,Marketing Analytics,4.696203,nd028,76,beginner,"[{'rating': 5, 'count': 63, 'percentage': 79.7...",8,"[digital marketing, google, Data Analytics, Da..."
10,Data Visualization,4.688889,nd197,45,beginner,"[{'rating': 5, 'count': 35, 'percentage': 77.7...",4,"[data visualization, Build Dashboard, Dashboar..."
30,Digital Marketing,4.681858,nd018,663,beginner,"[{'rating': 5, 'count': 895, 'percentage': 78....",8,"[No Coding, Social Media Marketing, Social Med..."
19,Introduction to Programming,4.627980,nd000,1215,beginner,"[{'rating': 5, 'count': 1660, 'percentage': 74...",5,"[python, css, html, javascript, HTML, CSS, Pyt..."
26,Business Analyst,4.570621,nd008,162,beginner,"[{'rating': 5, 'count': 259, 'percentage': 73....",9,[]
36,Data Foundations for Enterprise,4.568000,nd100-ent,52,beginner,"[{'rating': 5, 'count': 102, 'percentage': 81....",4,[]
25,Business Analyst for Enterprise,4.548387,nd008-ent,11,beginner,"[{'rating': 5, 'count': 22, 'percentage': 70.9...",9,[]
46,Design Sprint Foundations,4.547945,nd201,46,beginner,"[{'rating': 5, 'count': 100, 'percentage': 68....",4,[]
44,Google Ads,4.500000,nd124,7,beginner,"[{'rating': 5, 'count': 24, 'percentage': 70.5...",2,[]
8,AI Product Manager,4.252252,nd088,215,beginner,"[{'rating': 5, 'count': 126, 'percentage': 56....",3,"[AI Product Manager, AI in business, ML in bus..."
32,Mobile Web Specialist,4.807229,nd024,163,advanced,"[{'rating': 5, 'count': 287, 'percentage': 86....",3,[]
28,Self Driving Car Engineer,4.746765,nd013,520,advanced,"[{'rating': 5, 'count': 897, 'percentage': 82....",14,"[Computer Vision, Sensor Fusion, Localization,..."
9,Sensor Fusion Engineer,4.720930,nd313,82,advanced,"[{'rating': 5, 'count': 67, 'percentage': 77.9...",4,"[Lidar, Radar, Kalman Filters, Radar Calibrati..."
27,Machine Learning Engineer,4.533333,nd009t,247,advanced,"[{'rating': 5, 'count': 249, 'percentage': 72....",4,"[python, Machine Learning, Deep learning, AI, ..."

---

### beginner nanodegrees

In [31]:

beginner_df = sorted_df[sorted_df["level"] == "beginner"]
beginner_df.head()

,title,average_rating,key,count,level,stats,num_of_projects,tags
52,Android Basics,4.846098,nd803,1399,beginner,"[{'rating': 5, 'count': 2415, 'percentage': 88...",12,"[mobile, apps, development, android, App Devel..."
16,Programming for Data Science with R,4.833333,nd118,12,beginner,"[{'rating': 5, 'count': 10, 'percentage': 83.3...",3,"[R, nd118, SQL, Advance SQl, Basic Data Scienc..."
13,Intro to Machine Learning with PyTorch,4.748148,nd229,129,beginner,"[{'rating': 5, 'count': 105, 'percentage': 77....",4,"[pyhton, python, sql, predictive, supervised, ..."
38,Programming for Data Science with Python,4.702381,nd104,239,beginner,"[{'rating': 5, 'count': 195, 'percentage': 77....",3,"[Data Analytics, SQL, SQL join, Python, Numpy,..."
18,Marketing Analytics,4.696203,nd028,76,beginner,"[{'rating': 5, 'count': 63, 'percentage': 79.7...",8,"[digital marketing, google, Data Analytics, Da..."
10,Data Visualization,4.688889,nd197,45,beginner,"[{'rating': 5, 'count': 35, 'percentage': 77.7...",4,"[data visualization, Build Dashboard, Dashboar..."
30,Digital Marketing,4.681858,nd018,663,beginner,"[{'rating': 5, 'count': 895, 'percentage': 78....",8,"[No Coding, Social Media Marketing, Social Med..."
19,Introduction to Programming,4.627980,nd000,1215,beginner,"[{'rating': 5, 'count': 1660, 'percentage': 74...",5,"[python, css, html, javascript, HTML, CSS, Pyt..."
26,Business Analyst,4.570621,nd008,162,beginner,"[{'rating': 5, 'count': 259, 'percentage': 73....",9,[]
36,Data Foundations for Enterprise,4.568000,nd100-ent,52,beginner,"[{'rating': 5, 'count': 102, 'percentage': 81....",4,[]
25,Business Analyst for Enterprise,4.548387,nd008-ent,11,beginner,"[{'rating': 5, 'count': 22, 'percentage': 70.9...",9,[]
46,Design Sprint Foundations,4.547945,nd201,46,beginner,"[{'rating': 5, 'count': 100, 'percentage': 68....",4,[]
44,Google Ads,4.500000,nd124,7,beginner,"[{'rating': 5, 'count': 24, 'percentage': 70.5...",2,[]
8,AI Product Manager,4.252252,nd088,215,beginner,"[{'rating': 5, 'count': 126, 'percentage': 56....",3,"[AI Product Manager, AI in business, ML in bus..."

---

### intermediate nanodegrees

In [34]:
intermediate_df = sorted_df[sorted_df["level"] == "intermediate"]
intermediate_df

,title,average_rating,key,count,level,stats,num_of_projects,tags
50,Android Developer,4.734921,nd801,901,intermediate,"[{'rating': 5, 'count': 1616, 'percentage': 81...",14,"[android, App Development, Android App Develop..."
21,Become a Data Analyst,4.722488,nd002-ent,161,intermediate,"[{'rating': 5, 'count': 170, 'percentage': 81....",22,"[r, hadoop, python, d3]"
42,Intro to Self-Driving Cars,4.680217,nd113,224,intermediate,"[{'rating': 5, 'count': 288, 'percentage': 78....",8,"[Self Driving Car, Automation, Bayesian Thinki..."
24,Predictive Analytics for Business,4.641667,nd008t,106,intermediate,"[{'rating': 5, 'count': 91, 'percentage': 75.8...",8,"[Data Analytics, No Coding, Alyterx, Tableau, ..."
37,Deep Learning,4.639004,nd101,1043,intermediate,"[{'rating': 5, 'count': 1661, 'percentage': 76...",5,"[Neural Network, AI, Pytorch, Numpy, CNN, Mach..."
22,iOS Developer,4.610306,nd003,301,intermediate,"[{'rating': 5, 'count': 456, 'percentage': 73....",14,"[swift, iOS, Swift, Make App, Make iOS App, Bu..."
31,React,4.588435,nd019,308,intermediate,"[{'rating': 5, 'count': 451, 'percentage': 76....",3,"[React, Front-end , Redux, React Native, React..."
5,Front End Web Developer,4.556561,nd0011,221,intermediate,"[{'rating': 5, 'count': 159, 'percentage': 71....",6,"[object oriented, object-oriented, UI, UX, Use..."
15,Data Structures and Algorithms,4.547872,nd256,181,intermediate,"[{'rating': 5, 'count': 143, 'percentage': 76....",4,"[big O notiation, recursion, trees, maps, hash..."
6,Full Stack Web Developer,4.536585,nd0044,164,intermediate,"[{'rating': 5, 'count': 109, 'percentage': 66....",5,"[computer science, front-end, frontend, javasc..."
17,Data Engineer,4.481229,nd027,283,intermediate,"[{'rating': 5, 'count': 197, 'percentage': 67....",6,"[data pipelines, data lakes, Data model, Apach..."
12,Cloud DevOps Engineer,4.474860,nd9991,179,intermediate,"[{'rating': 5, 'count': 116, 'percentage': 64....",5,"[cloud, devops, Cloud Basics, Cloud Foundation..."
14,C++,4.466368,nd213,219,intermediate,"[{'rating': 5, 'count': 149, 'percentage': 66....",5,"[classes, structures, pointers, leakage, funct..."
11,Cloud Developer,4.376404,nd9990,177,intermediate,"[{'rating': 5, 'count': 116, 'percentage': 65....",5,"[cloud engineering, Cloud Basics, Cloud Founda..."
29,VR Developer,4.348243,nd017,159,intermediate,"[{'rating': 5, 'count': 210, 'percentage': 67....",13,"[unity, vr, virtual reality, unreal]"
7,Java Developer,2.906250,nd035,32,intermediate,"[{'rating': 5, 'count': 7, 'percentage': 21.87...",4,"[Persistent layers, Jenkins, CI/CD, Microservi..."

---

### advanced nanodegrees

In [35]:
advanced_df = sorted_df[sorted_df["level"] == "advanced"]

advanced_df

,title,average_rating,key,count,level,stats,num_of_projects,tags
32,Mobile Web Specialist,4.807229,nd024,163,advanced,"[{'rating': 5, 'count': 287, 'percentage': 86....",3,[]
28,Self Driving Car Engineer,4.746765,nd013,520,advanced,"[{'rating': 5, 'count': 897, 'percentage': 82....",14,"[Computer Vision, Sensor Fusion, Localization,..."
9,Sensor Fusion Engineer,4.720930,nd313,82,advanced,"[{'rating': 5, 'count': 67, 'percentage': 77.9...",4,"[Lidar, Radar, Kalman Filters, Radar Calibrati..."
27,Machine Learning Engineer,4.533333,nd009t,247,advanced,"[{'rating': 5, 'count': 249, 'percentage': 72....",4,"[python, Machine Learning, Deep learning, AI, ..."